nome = str(input('Olá! Tudo bem? Por favor, digite seu nome completo: ')).strip().upper()
letra = str(input('Escolha uma letra.')).strip().upper()
nome1 = nome.split()
#data = int(input('Em que ano você nasceu?'))
print('Os dados foram analisados, veja os resultados abaixo.')
print('Seu nome tem {} letras no total.'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é {}: '.format(nome1[0]))
print('Seu último nome é {}: '.format(nome1[len(nome1) - 1]))
#print('A letra {} aparece {} vezes no seu nome.'.format(letra, letra.count('letra')))
